# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tffg1156-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/project_1/project_1.cache/wt [current_project]
set_property parent.project_path Z:/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
set_property loop_count 20000 [current_fileset]
read_verilog -library xil_defaultlib {
  Z:/project_1/project_1.srcs/sources_1/new/lfsr.v
  Z:/project_1/project_1.srcs/sources_1/new/add_with_saturate.v
  Z:/project_1/project_1.srcs/sources_1/new/max2.v
  Z:/project_1/project_1.srcs/sources_1/new/sub_with_saturate.v
  Z:/project_1/project_1.srcs/sources_1/new/sigma_prime.v
  Z:/project_1/project_1.srcs/sources_1/new/sigma.v
  Z:/project_1/project_1.srcs/sources_1/new/stochastic_quantizer.v
  Z:/project_1/project_1.srcs/sources_1/new/fc16x1.v
  Z:/project_1/project_1.srcs/sources_1/new/pool2x2.v
  Z:/project_1/project_1.srcs/sources_1/new/filter3x3.v
  Z:/project_1/project_1.srcs/sources_1/new/fc_gr_update16x1.v
  Z:/project_1/project_1.srcs/sources_1/new/fc_bp16x1.v
  Z:/project_1/project_1.srcs/sources_1/new/top_cnn.v
}
synth_design -top top_cnn -part xc7a200tffg1156-3 -mode out_of_context
write_checkpoint -noxdef top_cnn.dcp
catch { report_utilization -file top_cnn_utilization_synth.rpt -pb top_cnn_utilization_synth.pb }
