# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tffg1156-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/VGGNet-16/VGGNet-16.cache/wt [current_project]
set_property parent.project_path Z:/VGGNet-16/VGGNet-16.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo z:/VGGNet-16/VGGNet-16.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property loop_count 20000 [current_fileset]
read_verilog -library xil_defaultlib {
  Z:/VGGNet-16/VGGNet-16.srcs/sources_1/new/lfsr.v
  Z:/VGGNet-16/VGGNet-16.srcs/sources_1/new/add_with_saturate.v
  Z:/VGGNet-16/VGGNet-16.srcs/sources_1/new/max2.v
  Z:/VGGNet-16/VGGNet-16.srcs/sources_1/new/sub_with_saturate.v
  Z:/VGGNet-16/VGGNet-16.srcs/sources_1/new/sigma_prime.v
  Z:/VGGNet-16/VGGNet-16.srcs/sources_1/new/sigma.v
  Z:/VGGNet-16/VGGNet-16.srcs/sources_1/new/stochastic_quantizer.v
  Z:/VGGNet-16/VGGNet-16.srcs/sources_1/new/fc16x1.v
  Z:/VGGNet-16/VGGNet-16.srcs/sources_1/new/pool2x2.v
  Z:/VGGNet-16/VGGNet-16.srcs/sources_1/new/filter3x3.v
  Z:/VGGNet-16/VGGNet-16.srcs/sources_1/new/fc_gr_update16x1.v
  Z:/VGGNet-16/VGGNet-16.srcs/sources_1/new/fc_bp16x1.v
  Z:/VGGNet-16/VGGNet-16.srcs/sources_1/new/top_cnn.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top top_cnn -part xc7a200tffg1156-3 -flatten_hierarchy full -directive RuntimeOptimized -retiming -mode out_of_context


write_checkpoint -force -noxdef top_cnn.dcp

catch { report_utilization -file top_cnn_utilization_synth.rpt -pb top_cnn_utilization_synth.pb }
